const $=id=>document.getElementById(id);
const state={data:null,pair:null,theme:'light'};
const pairNames={'1x1':'Nearby sources','1x5':'Nearby and distant sources','5x5':'Distant sources'};
const palette={light:{ink:'#172033',muted:'#687083',grid:'#dce1e8',point:'#2457d6',error:'#df5b3f'},dark:{ink:'#f3f5f8',muted:'#aeb7c7',grid:'#334055',point:'#88aaff',error:'#ff8c72'}};
function fmt(v,d=3){return Number(v).toLocaleString('en-GB',{maximumFractionDigits:d})}
function sci(v){const [a,b]=Number(v).toExponential(2).split('e');const supers={'0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹','-':'⁻'};return `${a} × 10${[...b.replace('+','')].map(x=>supers[x]||x).join('')}`}
function currentPair(){return state.data.pairs.find(p=>p.id===state.pair)}
function redshift(bin){return state.data.redshift_distributions.find(row=>row.bin===bin)}
function prepare(canvas,ratio=.54){const dpr=Math.min(devicePixelRatio||1,2),w=Math.max(300,Math.round(canvas.getBoundingClientRect().width)),h=Math.round(w*ratio);canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w,h}}
function colours(){return palette[state.theme]}
function drawShear(){const p=currentPair(),{ctx,w,h}=prepare($('shearChart')),{ink,muted,grid,point,error}=colours(),m={l:82,r:26,t:26,b:64};ctx.clearRect(0,0,w,h);const lo=Math.min(...p.xi_plus.map((v,i)=>v-p.sigma[i])),hi=Math.max(...p.xi_plus.map((v,i)=>v+p.sigma[i])),pad=(hi-lo)*.12||1e-6,minY=lo-pad,maxY=hi+pad,minX=Math.log10(p.theta_arcmin[0]),maxX=Math.log10(p.theta_arcmin.at(-1));const sx=x=>m.l+(Math.log10(x)-minX)/(maxX-minX)*(w-m.l-m.r),sy=y=>m.t+(maxY-y)/(maxY-minY)*(h-m.t-m.b);ctx.font='12px system-ui';ctx.fillStyle=muted;ctx.strokeStyle=grid;ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=m.t+(h-m.t-m.b)*i/4,val=maxY-(maxY-minY)*i/4;ctx.beginPath();ctx.moveTo(m.l,y);ctx.lineTo(w-m.r,y);ctx.stroke();ctx.fillText(sci(val),6,y+4)}[1,3,10,30,100,200].forEach(v=>{const x=sx(v);ctx.beginPath();ctx.moveTo(x,m.t);ctx.lineTo(x,h-m.b);ctx.stroke();ctx.fillText(v,x-8,h-m.b+22)});if(minY<0&&maxY>0){ctx.strokeStyle=ink;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(m.l,sy(0));ctx.lineTo(w-m.r,sy(0));ctx.stroke();ctx.setLineDash([])}p.theta_arcmin.forEach((x,i)=>{const px=sx(x),py=sy(p.xi_plus[i]),top=sy(p.xi_plus[i]+p.sigma[i]),bottom=sy(p.xi_plus[i]-p.sigma[i]);ctx.strokeStyle=error;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px,top);ctx.lineTo(px,bottom);ctx.moveTo(px-5,top);ctx.lineTo(px+5,top);ctx.moveTo(px-5,bottom);ctx.lineTo(px+5,bottom);ctx.stroke();ctx.fillStyle=point;ctx.beginPath();ctx.arc(px,py,5.5,0,Math.PI*2);ctx.fill()});ctx.fillStyle=ink;ctx.font='600 13px system-ui';ctx.fillText('angular separation θ [arcmin]',w/2-86,h-14);ctx.save();ctx.translate(18,h/2+28);ctx.rotate(-Math.PI/2);ctx.fillText('shape correlation ξ+',0,0);ctx.restore()}
function drawRedshift(){const p=currentPair(),bins=[...new Set([p.bin1,p.bin2])],rows=bins.map(redshift),{ctx,w,h}=prepare($('redshiftChart'),.48),{ink,muted,grid,point,error}=colours(),m={l:55,r:22,t:24,b:48},seriesColours=[point,error],maxY=Math.max(...rows.flatMap(r=>r.density)),sx=x=>m.l+x/2.2*(w-m.l-m.r),sy=y=>m.t+(maxY-y)/maxY*(h-m.t-m.b);ctx.clearRect(0,0,w,h);ctx.strokeStyle=grid;ctx.fillStyle=muted;ctx.font='12px system-ui';for(let i=0;i<=4;i++){const x=m.l+(w-m.l-m.r)*i/4;ctx.beginPath();ctx.moveTo(x,m.t);ctx.lineTo(x,h-m.b);ctx.stroke();ctx.fillText(fmt(2.2*i/4,1),x-7,h-m.b+20)}rows.forEach((row,index)=>{ctx.strokeStyle=seriesColours[index];ctx.lineWidth=3;ctx.beginPath();row.z_mid.forEach((z,i)=>{const x=sx(z),y=sy(row.density[i]);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=seriesColours[index];ctx.fillText(`bin ${row.bin} · mean z ${fmt(row.mean_z,2)}`,m.l+10,m.t+18+index*20)});ctx.fillStyle=ink;ctx.font='600 13px system-ui';ctx.fillText('photometric redshift z',w/2-62,h-10)}
function language(pair){const p=pair.null_p_value;if(p<.001)return['Strong evidence against zero shear',`The nine values are jointly inconsistent with ξ+ = 0 (p ${p<1e-6?'< 10⁻⁶':'= '+p.toPrecision(2)}). Their covariance-aware distance is ${fmt(pair.correlated_snr,1)}.`];if(p<.05)return['Evidence against zero shear',`This vector is unlikely under ξ+ = 0 (p = ${p.toPrecision(2)}), although it is not a cosmological fit.`];return['This pair alone is not decisive',`This nine-point vector is compatible with zero shear at conventional thresholds (p = ${fmt(p,2)}). Combining tomographic pairs carries much more information.`]}
function render(){const p=currentPair(),z1=redshift(p.bin1),z2=redshift(p.bin2),name=pairNames[p.id]||`Tomographic bins ${p.bin1} × ${p.bin2}`;document.querySelectorAll('[data-pair]').forEach(b=>{const active=b.dataset.pair===p.id;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});$('pairSelect').value=p.id;$('chartTitle').textContent=`${name}: bins ${p.bin1} × ${p.bin2}`;$('chartSummary').textContent=`Nine observed ξ+ measurements from ${fmt(p.theta_arcmin[0],2)} to ${fmt(p.theta_arcmin.at(-1),1)} arcmin. Error bars are marginal 1σ values; the result card uses the full covariance.`;const [title,text]=language(p);$('findingTitle').textContent=title;$('findingText').textContent=text;$('snrValue').textContent=fmt(p.correlated_snr,2);$('pValue').textContent=p.null_p_value<1e-6?p.null_p_value.toExponential(2):fmt(p.null_p_value,4);$('meanZValue').textContent=p.bin1===p.bin2?fmt(z1.mean_z,2):`${fmt(z1.mean_z,2)} × ${fmt(z2.mean_z,2)}`;$('depthText').textContent=p.bin1===p.bin2?`Both galaxies come from source bin ${p.bin1}, whose released n(z) has mean z ≈ ${fmt(z1.mean_z,2)}. ${p.bin1>=4?'Their light traverses a long foreground path, making accumulated shear easier to see.':'The shorter path contains less lensing structure, so this one pair has limited power.'}`:`This cross-correlation compares bins ${p.bin1} and ${p.bin2}. Only structure in front of both populations contributes coherently; their mean redshifts are ${fmt(z1.mean_z,2)} and ${fmt(z2.mean_z,2)}.`;$('depthScaleLabel').textContent=p.bin1===p.bin2?`bin ${p.bin1} · z̄ ${fmt(z1.mean_z,2)}`:`bins ${p.bin1}/${p.bin2}`;$('dataRows').innerHTML=p.theta_arcmin.map((x,i)=>`<tr><td>${fmt(x,3)}</td><td>${sci(p.xi_plus[i])}</td><td>${sci(p.sigma[i])}</td><td>${fmt(p.xi_plus[i]/p.sigma[i],2)}</td></tr>`).join('');drawShear();drawRedshift()}
function selectPair(id){state.pair=id;history.replaceState(null,'',`#pair=${id}`);render()}
function download(){const p=currentPair(),rows=['theta_arcmin,xi_plus,sigma',...p.theta_arcmin.map((x,i)=>`${x},${p.xi_plus[i]},${p.sigma[i]}`)],blob=new Blob([rows.join('\n')+'\n'],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kids1000-xip-${p.id}.csv`;a.click();URL.revokeObjectURL(a.href)}
function applyTheme(next){state.theme=next;document.documentElement.dataset.theme=next;$('themeToggle').textContent=next==='dark'?'Day mode':'Night mode';localStorage.setItem('shear-theme',next);if(state.data)render()}
async function init(){const response=await fetch('data/kids1000-xip.json');if(!response.ok)throw Error(`KiDS data failed to load (${response.status})`);state.data=await response.json();$('pairSelect').innerHTML=state.data.pairs.map(p=>`<option value="${p.id}">Bins ${p.bin1} × ${p.bin2}</option>`).join('');const requested=location.hash.match(/pair=(\dx\d)/)?.[1];state.pair=state.data.pairs.some(p=>p.id===requested)?requested:'1x1';document.querySelectorAll('[data-pair]').forEach(button=>button.addEventListener('click',()=>selectPair(button.dataset.pair)));$('pairSelect').addEventListener('change',e=>selectPair(e.target.value));$('downloadCsv').addEventListener('click',download);$('themeToggle').addEventListener('click',()=>applyTheme(state.theme==='dark'?'light':'dark'));addEventListener('resize',()=>{clearTimeout(window.redrawTimer);window.redrawTimer=setTimeout(render,120)});applyTheme(localStorage.getItem('shear-theme')||'light')}
init().catch(error=>{$('findingTitle').textContent='Data could not be loaded';$('findingText').textContent=error.message});
